### ISSUE TITLE
Ouput gem ver with CLI

### ISSUE THREAD

**Issue by brettchalupa** [brettchalupa/graphql-docs#145]
`graphql-docs -v` or `graphql-docs --version` to output the gem version so people know which version they're running

**Comment by JoanLn** [comment]
Hi @brettchalupa, May I work on this? If yes, please assign this issue to me, thanks!

**Comment by brettchalupa** [comment]
@JoanLn go for it, thank you! 🙌

**Comment by JoanLn** [comment]
@brettchalupa Just want to clarify, do you want to show the version of graphql-docs as well, or just for gem?
Here's the result I recently have.
![image](https://github.com/brettchalupa/graphql-docs/assets/117309623/8c026420-51c7-4767-a75b-c633698905cb)

As the contributing guide says, I have to ensure tests pass by running bin/rake, but I kept getting error("Command failed with status (127)").   Here' the error message.
![image](https://github.com/brettchalupa/graphql-docs/assets/117309623/850bcec0-f72f-411b-bce1-234db8c1fa8b)
I could run the ruby command direclty, though the result was failed.
![image](https://github.com/brettchalupa/graphql-docs/assets/117309623/f8a8ede0-463c-41d9-bf3e-9bbc85d313be)


May I ask some help for this?
Thanks!

**Comment by brettchalupa** [comment]
@JoanLn happy to help! Nice progress so far. 🙌 

Here's some more info on what I'd expect from this addition:

User runs this command:

```
$ graphql-docs -v
v4.0.0
```

and it outputs the version from `GraphQLDocs::VERSION` constant, defined in this file: https://github.com/brettchalupa/graphql-docs/blob/main/lib/graphql-docs/version.rb#L4

A stretch goal would be to support `--version` too, a longer version of the CLI flag.

That `VERSION` constant gets updated whenever there's a new release, so it's a reliable way to know what version is installed.

That's strange about `bin/rake` but I'd say don't worry about it. If you can get a PR open, the tests will run automatically on GitHub. They may fail due to https://github.com/brettchalupa/graphql-docs/issues/143 but I'll try to fix that soon.

Let me know if I can be of any additional help.

**Comment by JoanLn** [comment]
Hi @brettchalupa 

Here's what I made so far:
![image](https://github.com/brettchalupa/graphql-docs/assets/117309623/6470184c-a58e-4863-95a2-dea0d5c3b06c)

The user can use graphql-docs -v/--version to query the version infromation.
I modify the version.rb file to see if the it will get updated when new version is installed, and it seems work.

Please let me know if anything need to be changed, or I can open a PR.

**Comment by brettchalupa** [comment]
@JoanLn looks great, thank you for taking this on. Looks like it's ready for a PR. :+1: :raised_hands:
