### ISSUE TITLE
Ruby sass is deprecated

### ISSUE THREAD

**Issue by ersinakinci** [brettchalupa/graphql-docs#86]
I noticed that this project uses the old `sass` gem. When I install `graphql-docs`, it complains that this gem is deprecated, etc. There's more info on the deprecation [here](https://sass-lang.com/ruby-sass).

Looks like `sassc` is suggested as a drop-in replacement. Any possibility that we could switch over?

**Comment by brettchalupa** [comment]
I'm going to work on trying to swap out sass for sassc or dartsass **or** remove Sass altogether and just use normal ole CSS to reduce the dependency load. I'm hoping to have that ready for the next release. 👍
